name: formify
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Core
  dio: ^5.9.0
  pretty_dio_logger: ^1.3.1
  get: ^4.6.6
  get_it: ^9.2.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  logging: ^1.3.0


  # Localization / UI
  easy_localization: ^3.0.7
  flutter_screenutil: ^5.9.3
  flutter_spinkit: ^5.2.1
  responsive_framework: ^1.5.1
  lottie: ^3.1.2
  shimmer: ^3.0.0
  smooth_page_indicator: ^2.0.1
  marquee: ^2.3.0
  animated_text_kit: ^4.3.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.4
  flutter_html: ^3.0.0-beta.2
  font_awesome_flutter: ^10.8.0
  flutter_animated_button: ^2.0.4
  dynamic_color: ^1.8.1

  # Forms
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.2.0
  form_builder_extra_fields: ^12.1.0
  custom_dropdown_search: ^1.0.0

  # Storage / permissions
  sqflite: ^2.4.2
  permission_handler: ^12.0.1
  image_picker: ^1.1.2
  internet_connection_checker_plus: ^2.5.2
  timezone: ^0.11.0
  flutter_phoenix: ^1.1.1

  # State management
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1

  # Serialization
  json_annotation: ^4.9.0
  retrofit: 4.9.2
  excel: ^4.0.6
  path_provider: ^2.1.5
  open_file: ^3.5.11
  fl_chart: ^1.1.1
  syncfusion_flutter_charts: ^32.2.8
  share_plus: ^12.0.1
  device_info_plus: ^12.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  retrofit_generator: ^10.2.1
  json_serializable: ^6.9.5
  freezed: ^3.2.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/onboarding/json/
    - assets/images/onboarding/
    - assets/images/main/
    - assets/images/home/
    - assets/json/
    - assets/images/

  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai/Almarai-Regular.ttf
          weight: 400
        - asset: assets/fonts/Almarai/Almarai-Bold.ttf
          weight: 700
        - asset: assets/fonts/Almarai/Almarai-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Almarai/Almarai-Light.ttf
          weight: 300
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Tajawal/Tajawal-Light.ttf
          weight: 300

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/main/logo.png"
  adaptive_icon_foreground: "assets/images/main/logo.png"
  adaptive_icon_background: "#3F7FBF"
  min_sdk_android: 21

flutter_native_splash:
  color: "#3F7FBF"
  image: assets/images/main/splash_screen1.png
  android_12:
    color: "#3F7FBF"
    image: assets/images/main/splash_screen1.png
  android: true
  ios: true
  android_gravity: fill
  ios_content_mode: scaleAspectFill
