

import 'package:formify/domain/models/models.dart';

class MockModel {

  static  List<DoctorMockItem> usersList = [
    DoctorMockItem(id: 1, name: "محمد دقاق"),
    DoctorMockItem(id: 2, name: "خالد قولي"),
    DoctorMockItem(id: 3, name: "نور سواس"),
    DoctorMockItem(id: 4, name: "رزق الله كلش"),
    DoctorMockItem(id: 5, name: "جورج خزعل"),
    DoctorMockItem(id: 6, name: "طوني مصيص"),
    DoctorMockItem(id: 7, name: "يوسف فاعور"),
    DoctorMockItem(id: 8, name: "اسماعيل الزلق"),
    DoctorMockItem(id: 9, name: "خالد الحصان"),
    DoctorMockItem(id: 10, name: "أديب حسين"),
    DoctorMockItem(id: 11, name: "حسام ملحم"),
    DoctorMockItem(id: 12, name: "آية عبيد"),
    DoctorMockItem(id: 13, name: "مروة الغاوي"),
    DoctorMockItem(id: 14, name: "عبد الله ضاهر"),
    DoctorMockItem(id: 15, name: "مازن حيدر"),
    DoctorMockItem(id: 16, name: "أحمد تاجي"),
    DoctorMockItem(id: 17, name: "غزوان بويضاني"),
    DoctorMockItem(id: 18, name: "نضال نقول"),
    DoctorMockItem(id: 19, name: "أهم غزال"),
    DoctorMockItem(id: 20, name: "محمد أبو هلال"),
    DoctorMockItem(id: 21, name: "راغد هارون"),
    DoctorMockItem(id: 22, name: "محمود خليل"),
    DoctorMockItem(id: 23, name: "كمال العريبيد"),
    DoctorMockItem(id: 24, name: "باسم عبد الغني الأصلي"),
    DoctorMockItem(id: 25, name: "محمود زعيتر"),
    DoctorMockItem(id: 26, name: "حسين موسى"),
    DoctorMockItem(id: 27, name: "رهف جابرة"),
    DoctorMockItem(id: 28, name: "ريهام سليمان"),
    DoctorMockItem(id: 29, name: "يوسف لطيفة"),
    DoctorMockItem(id: 30, name: "ربى سايس"),
    DoctorMockItem(id: 31, name: "غيث صالح"),
    DoctorMockItem(id: 32, name: "اياد يانس"),
    DoctorMockItem(id: 33, name: "بسام العوا"),
    DoctorMockItem(id: 34, name: "أيمن الحلاق"),
    DoctorMockItem(id: 35, name: "إباء كيوان"),
    DoctorMockItem(id: 36, name: "عزة غانم"),
    DoctorMockItem(id: 37, name: "مازن الخليل"),
    DoctorMockItem(id: 38, name: "محمد الشقيري"),
    DoctorMockItem(id: 39, name: "عبادة الزين"),
    DoctorMockItem(id: 40, name: "عامر الحاج"),
    DoctorMockItem(id: 41, name: "أنس الدالي"),
    DoctorMockItem(id: 42, name: "مصعب قوقو"),
    DoctorMockItem(id: 43, name: "موفق عموري"),
    DoctorMockItem(id: 44, name: "هيثم شريف علي"),
    DoctorMockItem(id: 45, name: "ماسة المعري"),
    DoctorMockItem(id: 46, name: "نضال سعدون"),
    DoctorMockItem(id: 47, name: "مؤيد رجب"),
    DoctorMockItem(id: 48, name: "شام الصالح"),
    DoctorMockItem(id: 49, name: "نضال عبد الوهاب"),
    DoctorMockItem(id: 50, name: "ابراهيم المظلوم"),
    DoctorMockItem(id: 51, name: "آية كسيبي"),
    DoctorMockItem(id: 52, name: "ديا خلوف"),
    DoctorMockItem(id: 53, name: "ظلال الواو"),
    DoctorMockItem(id: 54, name: "محمد علي حجار"),
    DoctorMockItem(id: 55, name: "صميل وهبه"),
    DoctorMockItem(id: 56, name: "ضحى الفياض"),
    DoctorMockItem(id: 57, name: "دايانا عيوش"),
    DoctorMockItem(id: 58, name: "عزت كحال"),
    DoctorMockItem(id: 59, name: "جلال الدين شربا"),
  ];

}