 name: DoForma WorkFlow
 on: 
   push: 
     branches:
       - main
 jobs:
   example-jop:
     runs-on: ubuntu-latest
     steps:
        - name: print a welcome message
          run : ecoh "welcome to our first github action workflow"
       
